title: مؤسسة رمال الصحراء
email: your-email@example.com
description: >-
  مؤسسة رمال الصحراء: موردكم الأول لبطحاء الرياض وتيماء والرمل الأبيض في مكة. خدماتنا سريعة، أسعارنا تنافسية، ونلتزم بالجودة لمشاريع البناء.
url: "https://bat7a-makkah.com"
baseurl: ""
timezone: Asia/Riyadh
author: مؤسسة رمال الصحراء

# إعدادات GitHub Pages
github: [metadata]
theme: jekyll-theme-minimal

# تضمين المجلدات
include:
  - _includes
  - _layouts
  - assets

# استبعاد المجلدات (اختياري)
# exclude:
#   - README.md
